import React, { useState } from "react";
import "../styles/training.css";
import { useNavigate } from "react-router-dom";
import jsPDF from "jspdf";

const TrainingProgram = () => {
    const navigate = useNavigate();
    const [showModal, setShowModal] = useState(false);
    const [selectedProgram, setSelectedProgram] = useState(null);

    const programs = [
        { title: "🏁 Beginner Full-Body Program", short: "Perfect for newcomers learning the basics.", details: "Light weights, form training, mobility sessions, and gradual strength progression." },
        { title: "🔥 Weight Loss / Fat Burn Program", short: "High-intensity calorie-burning routine.", details: "HIIT, circuits, fat-burn cardio, and metabolic conditioning sessions." },
        { title: "💪 Muscle Gain (Hypertrophy)", short: "Maximize muscle growth and strength.", details: "High-volume workouts, progressive overload, and targeted muscle isolation." },
        { title: "🏋️ Strength Training (Power)", short: "Focused on heavy compound lifting.", details: "5×5 strength training, low reps, heavy weight, and progressive overload." },
        { title: "⚡ Athlete Conditioning Program", short: "Speed, agility, explosiveness.", details: "Plyometrics, sprints, explosive movements, and high-performance conditioning." },
        { title: "🏆 5-Day Bodybuilding Split", short: "Classic physique-building training.", details: "Body-part splits, high volume, and maximum muscle isolation." },
    ];

    const handleProgramClick = (program) => {
        setSelectedProgram(program);
        setShowModal(true);
    };

    const chooseYes = () => {
        setShowModal(false);
        navigate("/coaches");
    };

    const chooseNo = () => {
        setShowModal(false);

        if (selectedProgram) {
            const doc = new jsPDF("p", "mm", "a4");
            const logo = new Image();
            logo.src = require("../assets/logo.png");

            logo.onload = () => {
                doc.addImage(logo, "PNG", 80, 10, 50, 50);
                generatePDFContent(doc);
            };

            logo.onerror = () => {
                generatePDFContent(doc);
            };
        }

        setTimeout(() => navigate("/home"), 300);
    };

    const generatePDFContent = (doc) => {
        let y = 70;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(22);
        doc.text(selectedProgram.title, 105, y, { align: "center" });
        y += 15;

        doc.setFontSize(14);
        doc.text("Program Summary:", 20, y);
        y += 8;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(12);
        doc.text(doc.splitTextToSize(selectedProgram.short, 170), 20, y);
        y += 20;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text("Details:", 20, y);
        y += 8;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(12);
        doc.text(doc.splitTextToSize(selectedProgram.details, 170), 20, y);

        doc.setFont("helvetica", "italic");
        doc.setFontSize(10);
        doc.text("Generated by Bi To Tri Gym — Train Hard, Transform Harder.", 105, 290, { align: "center" });

        const safeTitle = selectedProgram.title.replace(/[^a-z0-9]/gi, "_");
        doc.save(`${safeTitle}_4-week-plan.pdf`);
    };

    const closeModal = () => setShowModal(false);

    return (
        <>
            <div className="program-container">
                <h1 className="program-title">Training Programs</h1>

                {/* SUBTITLE */}
                <p className="program-subtitle">
                    Structured plans built to match your goals, fitness level, and performance needs
                </p>

                <p className="program-intro">
                    Hover over a program to preview details, then click to continue.
                </p>

                {programs.map((p, index) => (
                    <div
                        key={index}
                        className="program-card hoverable clickable"
                        onClick={() => handleProgramClick(p)}
                    >
                        <h2>{p.title}</h2>
                        <p className="program-desc">{p.short}</p>

                        <div className="hover-details">
                            <p>{p.details}</p>
                            <span className="hover-tip">Click to continue →</span>
                        </div>
                    </div>
                ))}
            </div>

            {showModal && (
                <div className="modal-overlay" onClick={closeModal}>
                    <div className="modal-box" onClick={(e) => e.stopPropagation()}>
                        <h3>Do you want a coach for this program?</h3>
                        <p>Click outside to cancel</p>
                        <p>Pressing no will download a PDF of the selected program</p>

                        <div className="modal-buttons">
                            <button className="yes-btn" onClick={chooseYes}>Yes</button>
                            <button className="no-btn" onClick={chooseNo}>No</button>
                        </div>
                    </div>
                </div>
            )}
        </>
    );
};

export default TrainingProgram;
